"""empty message

Revision ID: 282f31bf16c4
Revises: None
Create Date: 2014-06-01 00:38:13.124060

"""

# revision identifiers, used by Alembic.
revision = '282f31bf16c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'public')
    ### end Alembic commands ###
